// Code generated by go generate; DO NOT EDIT.
package cloudflare

import "errors"

type Permission int

const (
	Invalid Permission = iota
	TokenVerify
	UserRead
	AccountRead
	ZoneRead
	TokensRead
)

var (
	PermissionStrings = map[Permission]string{
		TokenVerify: "token_verify",
		UserRead:    "user_read",
		AccountRead: "account_read",
		ZoneRead:    "zone_read",
		TokensRead:  "tokens_read",
	}

	StringToPermission = map[string]Permission{
		"token_verify": TokenVerify,
		"user_read":    UserRead,
		"account_read": AccountRead,
		"zone_read":    ZoneRead,
		"tokens_read":  TokensRead,
	}

	PermissionIDs = map[Permission]int{
		TokenVerify: 1,
		UserRead:    2,
		AccountRead: 3,
		ZoneRead:    4,
		TokensRead:  5,
	}

	IdToPermission = map[int]Permission{
		1: TokenVerify,
		2: UserRead,
		3: AccountRead,
		4: ZoneRead,
		5: TokensRead,
	}
)

func (p Permission) ToString() (string, error) {
	if str, ok := PermissionStrings[p]; ok {
		return str, nil
	}
	return "", errors.New("invalid permission")
}

func (p Permission) ToID() (int, error) {
	if id, ok := PermissionIDs[p]; ok {
		return id, nil
	}
	return 0, errors.New("invalid permission")
}

func PermissionFromString(s string) (Permission, error) {
	if p, ok := StringToPermission[s]; ok {
		return p, nil
	}
	return 0, errors.New("invalid permission string")
}

func PermissionFromID(id int) (Permission, error) {
	if p, ok := IdToPermission[id]; ok {
		return p, nil
	}
	return 0, errors.New("invalid permission ID")
}
