// Code generated by go generate; DO NOT EDIT.
package doppler

import "errors"

type Permission int

const (
	Invalid Permission = iota
	WorkplaceRead
	ProjectsRead
	ConfigsRead
	SecretsRead
	ScimAccess
	AuditRead
)

var (
	PermissionStrings = map[Permission]string{
		WorkplaceRead: "workplace_read",
		ProjectsRead:  "projects_read",
		ConfigsRead:   "configs_read",
		SecretsRead:   "secrets_read",
		ScimAccess:    "scim_access",
		AuditRead:     "audit_read",
	}

	StringToPermission = map[string]Permission{
		"workplace_read": WorkplaceRead,
		"projects_read":  ProjectsRead,
		"configs_read":   ConfigsRead,
		"secrets_read":   SecretsRead,
		"scim_access":    ScimAccess,
		"audit_read":     AuditRead,
	}

	PermissionIDs = map[Permission]int{
		WorkplaceRead: 1,
		ProjectsRead:  2,
		ConfigsRead:   3,
		SecretsRead:   4,
		ScimAccess:    5,
		AuditRead:     6,
	}

	IdToPermission = map[int]Permission{
		1: WorkplaceRead,
		2: ProjectsRead,
		3: ConfigsRead,
		4: SecretsRead,
		5: ScimAccess,
		6: AuditRead,
	}
)

func (p Permission) ToString() (string, error) {
	if str, ok := PermissionStrings[p]; ok {
		return str, nil
	}
	return "", errors.New("invalid permission")
}

func (p Permission) ToID() (int, error) {
	if id, ok := PermissionIDs[p]; ok {
		return id, nil
	}
	return 0, errors.New("invalid permission")
}

func PermissionFromString(s string) (Permission, error) {
	if p, ok := StringToPermission[s]; ok {
		return p, nil
	}
	return 0, errors.New("invalid permission string")
}

func PermissionFromID(id int) (Permission, error) {
	if p, ok := IdToPermission[id]; ok {
		return p, nil
	}
	return 0, errors.New("invalid permission ID")
}
