// Code generated by go generate; DO NOT EDIT.
package terraformcloud

import "errors"

type Permission int

const (
	Invalid           Permission = iota
	AccountRead       Permission = iota
	OrganizationsRead Permission = iota
	WorkspacesRead    Permission = iota
	VariablesRead     Permission = iota
	VarsetsRead       Permission = iota
)

var (
	PermissionStrings = map[Permission]string{
		AccountRead:       "account_read",
		OrganizationsRead: "organizations_read",
		WorkspacesRead:    "workspaces_read",
		VariablesRead:     "variables_read",
		VarsetsRead:       "varsets_read",
	}

	StringToPermission = map[string]Permission{
		"account_read":       AccountRead,
		"organizations_read": OrganizationsRead,
		"workspaces_read":    WorkspacesRead,
		"variables_read":     VariablesRead,
		"varsets_read":       VarsetsRead,
	}

	PermissionIDs = map[Permission]int{
		AccountRead:       1,
		OrganizationsRead: 2,
		WorkspacesRead:    3,
		VariablesRead:     4,
		VarsetsRead:       5,
	}

	IdToPermission = map[int]Permission{
		1: AccountRead,
		2: OrganizationsRead,
		3: WorkspacesRead,
		4: VariablesRead,
		5: VarsetsRead,
	}
)

// ToString converts a Permission enum to its string representation
func (p Permission) ToString() (string, error) {
	if str, ok := PermissionStrings[p]; ok {
		return str, nil
	}
	return "", errors.New("invalid permission")
}

// ToID converts a Permission enum to its ID
func (p Permission) ToID() (int, error) {
	if id, ok := PermissionIDs[p]; ok {
		return id, nil
	}
	return 0, errors.New("invalid permission")
}

// PermissionFromString converts a string representation to its Permission enum
func PermissionFromString(s string) (Permission, error) {
	if p, ok := StringToPermission[s]; ok {
		return p, nil
	}
	return 0, errors.New("invalid permission string")
}

// PermissionFromID converts an ID to its Permission enum
func PermissionFromID(id int) (Permission, error) {
	if p, ok := IdToPermission[id]; ok {
		return p, nil
	}
	return 0, errors.New("invalid permission ID")
}
