// Code generated by go generate; DO NOT EDIT.
package vercel

import "errors"

type Permission int

const (
	Invalid Permission = iota
	UserRead
	TeamsRead
	ProjectsRead
)

var (
	PermissionStrings = map[Permission]string{
		UserRead:     "user_read",
		TeamsRead:    "teams_read",
		ProjectsRead: "projects_read",
	}

	StringToPermission = map[string]Permission{
		"user_read":     UserRead,
		"teams_read":    TeamsRead,
		"projects_read": ProjectsRead,
	}

	PermissionIDs = map[Permission]int{
		UserRead:     1,
		TeamsRead:    2,
		ProjectsRead: 3,
	}

	IdToPermission = map[int]Permission{
		1: UserRead,
		2: TeamsRead,
		3: ProjectsRead,
	}
)

func (p Permission) ToString() (string, error) {
	if str, ok := PermissionStrings[p]; ok {
		return str, nil
	}
	return "", errors.New("invalid permission")
}

func (p Permission) ToID() (int, error) {
	if id, ok := PermissionIDs[p]; ok {
		return id, nil
	}
	return 0, errors.New("invalid permission")
}

func PermissionFromString(s string) (Permission, error) {
	if p, ok := StringToPermission[s]; ok {
		return p, nil
	}
	return 0, errors.New("invalid permission string")
}

func PermissionFromID(id int) (Permission, error) {
	if p, ok := IdToPermission[id]; ok {
		return p, nil
	}
	return 0, errors.New("invalid permission ID")
}
