// Code generated by go generate; DO NOT EDIT.
package hashicorpvault

import "errors"

type Permission int

const (
	Invalid Permission = iota
	LookupSelf
	ListMounts
)

var (
	PermissionStrings = map[Permission]string{
		LookupSelf: "lookup_self",
		ListMounts: "list_mounts",
	}

	StringToPermission = map[string]Permission{
		"lookup_self": LookupSelf,
		"list_mounts": ListMounts,
	}

	PermissionIDs = map[Permission]int{
		LookupSelf: 1,
		ListMounts: 2,
	}

	IdToPermission = map[int]Permission{
		1: LookupSelf,
		2: ListMounts,
	}
)

func (p Permission) ToString() (string, error) {
	if str, ok := PermissionStrings[p]; ok {
		return str, nil
	}
	return "", errors.New("invalid permission")
}

func (p Permission) ToID() (int, error) {
	if id, ok := PermissionIDs[p]; ok {
		return id, nil
	}
	return 0, errors.New("invalid permission")
}

func PermissionFromString(s string) (Permission, error) {
	if p, ok := StringToPermission[s]; ok {
		return p, nil
	}
	return 0, errors.New("invalid permission string")
}

func PermissionFromID(id int) (Permission, error) {
	if p, ok := IdToPermission[id]; ok {
		return p, nil
	}
	return 0, errors.New("invalid permission ID")
}
